name: budapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  pdf: ^3.10.7
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  camera: ^0.10.5+5
  vector_math: ^2.1.4
  permission_handler: ^11.3.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_analytics: ^11.3.3
  in_app_purchase: ^3.1.11
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  google_generative_ai: ^0.2.2
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.2.2
  connectivity_plus: ^5.0.2
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  
  # Assets
  assets:
    - photos/budapplogo.png
    - .env

# Localization settings
flutter_gen:
  integrations:
    flutter_localizations: true

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "photos/budapplogo.png"
  min_sdk_android: 21
  
  # Android Adaptive Icon (okrągła ikona)
  adaptive_icon_background: "#3A5A7C"  # Kolor tła z logo
  adaptive_icon_foreground: "photos/budapplogo.png"
  adaptive_icon_round: "photos/budapplogo.png"
  
  # iOS
  remove_alpha_ios: false